WinUI-2482_UG
syncfusion-content/winui-docs pull request #278
Opened 2022-06-14 13:40 UTC by YuvarajMasilamani

2022-06-14 13:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4427/console)**

2022-06-14 13:42 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4427/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4427/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4427/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4427/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4427/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4427/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4427/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-15 06:20 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4428/console)**

2022-06-15 06:23 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4428/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4428/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4428/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4428/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4428/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4428/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4428/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-22 12:27 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4451/console)**

2022-06-22 12:28 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4451/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4451/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4451/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4451/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4451/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4451/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4451/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-22 14:13 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4462/console)**

2022-06-22 14:14 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4462/artifact/cireports/)<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4462/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4462/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4462/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4462/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4462/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4462/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [1](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4462/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-23 06:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4465/console)**

2022-06-23 06:11 UTC, jeganraj-m commented
rebuild

2022-06-23 06:11 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4465/artifact/cireports/)<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4465/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4465/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4465/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4465/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4465/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4465/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [2](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4465/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-23 06:12 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4466/console)**

2022-06-23 06:12 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4466/artifact/cireports/)<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4466/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4466/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4466/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4466/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4466/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4466/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [2](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4466/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-23 07:21 UTC, jeganraj-m commented
rebuild

2022-06-23 07:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4467/console)**

2022-06-23 07:23 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4467/artifact/cireports/)<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4467/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4467/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4467/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4467/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4467/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4467/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [2](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4467/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-23 07:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4469/console)**

2022-06-23 07:32 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4469/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4469/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4469/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4469/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4469/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4469/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4469/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-24 05:15 UTC, jeganraj-m commented on winui/AutoComplete/Leading-and-Trailing-view.md
> +This section explains about the Leading and Trailing view support available in [AutoComplete](https://help.syncfusion.com/cr/winui/Syncfusion.UI.Xaml.Editors.SfAutoComplete.html).The `Leadingview` ap
Any content, such as an icon, image, button, or control,

2022-06-24 05:15 UTC, jeganraj-m commented on winui/AutoComplete/Leading-and-Trailing-view.md
> +![Trailing View in WinUI AutoComplete](Leading_and_Trailing_view_images/Trailing-View-in-AutoComplete.png)
WinUI AutoComplete control with button in trailing view
WinUI AutoComplete control with icon in leading view
WinUI AutoComplete control with combo box in leading view and button in trailing view

2022-06-24 05:15 UTC, jeganraj-m commented on winui/AutoComplete/Leading-and-Trailing-view.md
> +## Both Leading and Trailing View
Leading and Trailing View

2022-06-24 05:15 UTC, jeganraj-m commented on winui/AutoComplete/Leading-and-Trailing-view.md
> +description: Learn here all about Leading and Trailing View support in Syncfusion WinUI AutoComplete control and more.
Learn how to add leading and trailing view in Syncfusion WinUI AutoComplete control and more.

2022-06-24 06:18 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4479/console)**

2022-06-24 06:19 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4479/artifact/cireports/)<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4479/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4479/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4479/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4479/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4479/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [2](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4479/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4479/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-24 06:57 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4480/console)**

2022-06-24 06:58 UTC, SyncfusionBuild commented
**CI Status: FAILURE :x:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Failure Reason: [CI Failure with violation](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4480/artifact/cireports/)<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4480/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [6](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4480/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4480/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4480/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4480/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4480/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4480/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-24 07:22 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4481/console)**

2022-06-24 07:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4481/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4481/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4481/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4481/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4481/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4481/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4481/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-27 05:14 UTC, florenceliliana requested changes

2022-06-27 05:14 UTC, florenceliliana commented on winui/AutoComplete/Leading-and-Trailing-view.md
> +This section explains about the leading and trailing view support available in [AutoComplete](https://help.syncfusion.com/cr/winui/Syncfusion.UI.Xaml.Editors.SfAutoComplete.html).The `LeadingView` ap
This section explains about the leading and trailing view support available in [AutoComplete](https://help.syncfusion.com/cr/winui/Syncfusion.UI.Xaml.Editors.SfAutoComplete.html). The `LeadingView` appears before the `AutoComplete` selection area and `TrailingView` appears after the `AutoComplete` selection area. Any content, such as an icon, image, button, or control, can be displayed in the `LeadingView` and `TrailingView.`

2022-06-27 05:14 UTC, florenceliliana commented on winui/ComboBox/Leading-and-Trailing-View.md
> +This section explains about the leading and trailing view support available in [ComboBox](https://help.syncfusion.com/cr/winui/Syncfusion.UI.Xaml.Editors.SfComboBox.html).The `LeadingView` appears be
This section explains about the leading and trailing view support available in [ComboBox](https://help.syncfusion.com/cr/winui/Syncfusion.UI.Xaml.Editors.SfComboBox.html). The `LeadingView` appears before the `ComboBox` selection area, and `TrailingView` appears after the `ComboBox` selection area. Any content, such as an icon, image, button, or control, can be displayed in the `LeadingView` and `TrailingView.`

2022-06-28 06:36 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4510/console)**

2022-06-28 06:37 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [WinUI-2482_Leading_and_Trailing_View_UG](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4510/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4510/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4510/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4510/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4510/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4510/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](http://jenkins.syncfusion.com/job/Content/job/winui-docs/4510/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>**

2022-06-28 06:38 UTC, jeganraj-m approved these changes

2022-06-28 06:38 UTC, merged